// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ad.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"` // NEW, USED, REFURBISHED
	ImageUrls     []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	SellerRating  float64                `protobuf:"fixed64,9,opt,name=seller_rating,json=sellerRating,proto3" json:"seller_rating,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ad) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Ad) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Ad) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Ad) GetSellerRating() float64 {
	if x != nil {
		return x.SellerRating
	}
	return 0
}

func (x *Ad) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Ad) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse) Reset() {
	*x = GetAdResponse{}
	mi := &file_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse) ProtoMessage() {}

func (x *GetAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse.ProtoReflect.Descriptor instead.
func (*GetAdResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type ListAdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PriceMin      int64                  `protobuf:"varint,3,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`
	PriceMax      int64                  `protobuf:"varint,4,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsRequest) Reset() {
	*x = ListAdsRequest{}
	mi := &file_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsRequest) ProtoMessage() {}

func (x *ListAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsRequest.ProtoReflect.Descriptor instead.
func (*ListAdsRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ListAdsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListAdsRequest) GetPriceMin() int64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *ListAdsRequest) GetPriceMax() int64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *ListAdsRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ListAdsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsResponse) Reset() {
	*x = ListAdsResponse{}
	mi := &file_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse) ProtoMessage() {}

func (x *ListAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse.ProtoReflect.Descriptor instead.
func (*ListAdsResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{6}
}

func (x *ListAdsResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *ListAdsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAdsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateAdRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AdId          string                  `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                             // optional
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // optional
	Price         *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`                             // optional
	CategoryId    *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // optional
	Condition     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`                     // optional
	Status        *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                           // optional (ACTIVE, INACTIVE, SOLD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdRequest) Reset() {
	*x = UpdateAdRequest{}
	mi := &file_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdRequest) ProtoMessage() {}

func (x *UpdateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *UpdateAdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAdRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateAdRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateAdRequest) GetPrice() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *UpdateAdRequest) GetCategoryId() *wrapperspb.StringValue {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

func (x *UpdateAdRequest) GetCondition() *wrapperspb.StringValue {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *UpdateAdRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdResponse) Reset() {
	*x = UpdateAdResponse{}
	mi := &file_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdResponse) ProtoMessage() {}

func (x *UpdateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{8}
}

type DeleteAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdRequest) Reset() {
	*x = DeleteAdRequest{}
	mi := &file_ad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdRequest) ProtoMessage() {}

func (x *DeleteAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAdRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *DeleteAdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdResponse) Reset() {
	*x = DeleteAdResponse{}
	mi := &file_ad_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdResponse) ProtoMessage() {}

func (x *DeleteAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{10}
}

type AttachMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachMediaRequest) Reset() {
	*x = AttachMediaRequest{}
	mi := &file_ad_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachMediaRequest) ProtoMessage() {}

func (x *AttachMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachMediaRequest.ProtoReflect.Descriptor instead.
func (*AttachMediaRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{11}
}

func (x *AttachMediaRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *AttachMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type AttachMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachMediaResponse) Reset() {
	*x = AttachMediaResponse{}
	mi := &file_ad_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachMediaResponse) ProtoMessage() {}

func (x *AttachMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachMediaResponse.ProtoReflect.Descriptor instead.
func (*AttachMediaResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{12}
}

type CreateAdWithImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // идентификатор пользователя (уже валидированный снаружи)
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	MediaIds      []string               `protobuf:"bytes,5,rep,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"` // идентификаторы уже загруженных медиа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdWithImagesRequest) Reset() {
	*x = CreateAdWithImagesRequest{}
	mi := &file_ad_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdWithImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdWithImagesRequest) ProtoMessage() {}

func (x *CreateAdWithImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdWithImagesRequest.ProtoReflect.Descriptor instead.
func (*CreateAdWithImagesRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAdWithImagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAdWithImagesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdWithImagesRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdWithImagesRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateAdWithImagesRequest) GetMediaIds() []string {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

type CreateAdWithImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdWithImagesResponse) Reset() {
	*x = CreateAdWithImagesResponse{}
	mi := &file_ad_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdWithImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdWithImagesResponse) ProtoMessage() {}

func (x *CreateAdWithImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdWithImagesResponse.ProtoReflect.Descriptor instead.
func (*CreateAdWithImagesResponse) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAdWithImagesResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

var File_ad_proto protoreflect.FileDescriptor

const file_ad_proto_rawDesc = "" +
	"\n" +
	"\bad.proto\x12\x02ad\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x02\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12#\n" +
	"\rseller_rating\x18\t \x01(\x01R\fsellerRating\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"x\n" +
	"\x0fCreateAdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\"*\n" +
	"\x10CreateAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"\x1e\n" +
	"\fGetAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\rGetAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"\xce\x01\n" +
	"\x0eListAdsRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tprice_min\x18\x03 \x01(\x03R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\x04 \x01(\x03R\bpriceMax\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"r\n" +
	"\x0fListAdsResponse\x12\x18\n" +
	"\x03ads\x18\x01 \x03(\v2\x06.ad.AdR\x03ads\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x97\x03\n" +
	"\x0fUpdateAdRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x05title\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x121\n" +
	"\x05price\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05price\x12=\n" +
	"\vcategory_id\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"categoryId\x12:\n" +
	"\tcondition\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tcondition\x124\n" +
	"\x06status\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x06status\"\x12\n" +
	"\x10UpdateAdResponse\"?\n" +
	"\x0fDeleteAdRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x12\n" +
	"\x10DeleteAdResponse\"D\n" +
	"\x12AttachMediaRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\"\x15\n" +
	"\x13AttachMediaResponse\"\x9f\x01\n" +
	"\x19CreateAdWithImagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1b\n" +
	"\tmedia_ids\x18\x05 \x03(\tR\bmediaIds\"4\n" +
	"\x1aCreateAdWithImagesResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad2\xa7\x03\n" +
	"\tAdService\x125\n" +
	"\bCreateAd\x12\x13.ad.CreateAdRequest\x1a\x14.ad.CreateAdResponse\x12,\n" +
	"\x05GetAd\x12\x10.ad.GetAdRequest\x1a\x11.ad.GetAdResponse\x122\n" +
	"\aListAds\x12\x12.ad.ListAdsRequest\x1a\x13.ad.ListAdsResponse\x125\n" +
	"\bUpdateAd\x12\x13.ad.UpdateAdRequest\x1a\x14.ad.UpdateAdResponse\x125\n" +
	"\bDeleteAd\x12\x13.ad.DeleteAdRequest\x1a\x14.ad.DeleteAdResponse\x12>\n" +
	"\vAttachMedia\x12\x16.ad.AttachMediaRequest\x1a\x17.ad.AttachMediaResponse\x12S\n" +
	"\x12CreateAdWithImages\x12\x1d.ad.CreateAdWithImagesRequest\x1a\x1e.ad.CreateAdWithImagesResponseB0Z.78-pflops/services/ad_service/pb/ad_service/pbb\x06proto3"

var (
	file_ad_proto_rawDescOnce sync.Once
	file_ad_proto_rawDescData []byte
)

func file_ad_proto_rawDescGZIP() []byte {
	file_ad_proto_rawDescOnce.Do(func() {
		file_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ad_proto_rawDesc), len(file_ad_proto_rawDesc)))
	})
	return file_ad_proto_rawDescData
}

var file_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ad_proto_goTypes = []any{
	(*Ad)(nil),                         // 0: ad.Ad
	(*CreateAdRequest)(nil),            // 1: ad.CreateAdRequest
	(*CreateAdResponse)(nil),           // 2: ad.CreateAdResponse
	(*GetAdRequest)(nil),               // 3: ad.GetAdRequest
	(*GetAdResponse)(nil),              // 4: ad.GetAdResponse
	(*ListAdsRequest)(nil),             // 5: ad.ListAdsRequest
	(*ListAdsResponse)(nil),            // 6: ad.ListAdsResponse
	(*UpdateAdRequest)(nil),            // 7: ad.UpdateAdRequest
	(*UpdateAdResponse)(nil),           // 8: ad.UpdateAdResponse
	(*DeleteAdRequest)(nil),            // 9: ad.DeleteAdRequest
	(*DeleteAdResponse)(nil),           // 10: ad.DeleteAdResponse
	(*AttachMediaRequest)(nil),         // 11: ad.AttachMediaRequest
	(*AttachMediaResponse)(nil),        // 12: ad.AttachMediaResponse
	(*CreateAdWithImagesRequest)(nil),  // 13: ad.CreateAdWithImagesRequest
	(*CreateAdWithImagesResponse)(nil), // 14: ad.CreateAdWithImagesResponse
	(*wrapperspb.StringValue)(nil),     // 15: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),      // 16: google.protobuf.Int64Value
}
var file_ad_proto_depIdxs = []int32{
	0,  // 0: ad.CreateAdResponse.ad:type_name -> ad.Ad
	0,  // 1: ad.GetAdResponse.ad:type_name -> ad.Ad
	0,  // 2: ad.ListAdsResponse.ads:type_name -> ad.Ad
	15, // 3: ad.UpdateAdRequest.title:type_name -> google.protobuf.StringValue
	15, // 4: ad.UpdateAdRequest.description:type_name -> google.protobuf.StringValue
	16, // 5: ad.UpdateAdRequest.price:type_name -> google.protobuf.Int64Value
	15, // 6: ad.UpdateAdRequest.category_id:type_name -> google.protobuf.StringValue
	15, // 7: ad.UpdateAdRequest.condition:type_name -> google.protobuf.StringValue
	15, // 8: ad.UpdateAdRequest.status:type_name -> google.protobuf.StringValue
	0,  // 9: ad.CreateAdWithImagesResponse.ad:type_name -> ad.Ad
	1,  // 10: ad.AdService.CreateAd:input_type -> ad.CreateAdRequest
	3,  // 11: ad.AdService.GetAd:input_type -> ad.GetAdRequest
	5,  // 12: ad.AdService.ListAds:input_type -> ad.ListAdsRequest
	7,  // 13: ad.AdService.UpdateAd:input_type -> ad.UpdateAdRequest
	9,  // 14: ad.AdService.DeleteAd:input_type -> ad.DeleteAdRequest
	11, // 15: ad.AdService.AttachMedia:input_type -> ad.AttachMediaRequest
	13, // 16: ad.AdService.CreateAdWithImages:input_type -> ad.CreateAdWithImagesRequest
	2,  // 17: ad.AdService.CreateAd:output_type -> ad.CreateAdResponse
	4,  // 18: ad.AdService.GetAd:output_type -> ad.GetAdResponse
	6,  // 19: ad.AdService.ListAds:output_type -> ad.ListAdsResponse
	8,  // 20: ad.AdService.UpdateAd:output_type -> ad.UpdateAdResponse
	10, // 21: ad.AdService.DeleteAd:output_type -> ad.DeleteAdResponse
	12, // 22: ad.AdService.AttachMedia:output_type -> ad.AttachMediaResponse
	14, // 23: ad.AdService.CreateAdWithImages:output_type -> ad.CreateAdWithImagesResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ad_proto_init() }
func file_ad_proto_init() {
	if File_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ad_proto_rawDesc), len(file_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_proto_goTypes,
		DependencyIndexes: file_ad_proto_depIdxs,
		MessageInfos:      file_ad_proto_msgTypes,
	}.Build()
	File_ad_proto = out.File
	file_ad_proto_goTypes = nil
	file_ad_proto_depIdxs = nil
}
