// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/ad.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"` // NEW, USED, REFURBISHED
	ImageUrls     []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	SellerRating  float64                `protobuf:"fixed64,9,opt,name=seller_rating,json=sellerRating,proto3" json:"seller_rating,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_proto_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ad) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Ad) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Ad) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Ad) GetSellerRating() float64 {
	if x != nil {
		return x.SellerRating
	}
	return 0
}

func (x *Ad) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Ad) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	Images        [][]byte               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"` // raw bytes for MediaService pass-through
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateAdRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateAdRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *CreateAdRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse) Reset() {
	*x = GetAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse) ProtoMessage() {}

func (x *GetAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse.ProtoReflect.Descriptor instead.
func (*GetAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type SearchAdsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CategoryId      string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PriceMin        int64                  `protobuf:"varint,3,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`
	PriceMax        int64                  `protobuf:"varint,4,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`
	Condition       string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	MinSellerRating float64                `protobuf:"fixed64,6,opt,name=min_seller_rating,json=minSellerRating,proto3" json:"min_seller_rating,omitempty"`
	Page            int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort            string                 `protobuf:"bytes,9,opt,name=sort,proto3" json:"sort,omitempty"` // price_asc, price_desc, created_desc
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchAdsRequest) Reset() {
	*x = SearchAdsRequest{}
	mi := &file_proto_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdsRequest) ProtoMessage() {}

func (x *SearchAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdsRequest.ProtoReflect.Descriptor instead.
func (*SearchAdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{5}
}

func (x *SearchAdsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchAdsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *SearchAdsRequest) GetPriceMin() int64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *SearchAdsRequest) GetPriceMax() int64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *SearchAdsRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *SearchAdsRequest) GetMinSellerRating() float64 {
	if x != nil {
		return x.MinSellerRating
	}
	return 0
}

func (x *SearchAdsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAdsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchAdsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type SearchAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAdsResponse) Reset() {
	*x = SearchAdsResponse{}
	mi := &file_proto_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdsResponse) ProtoMessage() {}

func (x *SearchAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdsResponse.ProtoReflect.Descriptor instead.
func (*SearchAdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{6}
}

func (x *SearchAdsResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *SearchAdsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchAdsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAdsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_ad_proto protoreflect.FileDescriptor

const file_proto_ad_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ad.proto\x12\x02ad\"\xc0\x02\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12#\n" +
	"\rseller_rating\x18\t \x01(\x01R\fsellerRating\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xb6\x01\n" +
	"\x0fCreateAdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x16\n" +
	"\x06images\x18\x06 \x03(\fR\x06images\"*\n" +
	"\x10CreateAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"\x1e\n" +
	"\fGetAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\rGetAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"\x90\x02\n" +
	"\x10SearchAdsRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tprice_min\x18\x03 \x01(\x03R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\x04 \x01(\x03R\bpriceMax\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12*\n" +
	"\x11min_seller_rating\x18\x06 \x01(\x01R\x0fminSellerRating\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04sort\x18\t \x01(\tR\x04sort\"t\n" +
	"\x11SearchAdsResponse\x12\x18\n" +
	"\x03ads\x18\x01 \x03(\v2\x06.ad.AdR\x03ads\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xaa\x01\n" +
	"\tAdService\x125\n" +
	"\bCreateAd\x12\x13.ad.CreateAdRequest\x1a\x14.ad.CreateAdResponse\x12,\n" +
	"\x05GetAd\x12\x10.ad.GetAdRequest\x1a\x11.ad.GetAdResponse\x128\n" +
	"\tSearchAds\x12\x14.ad.SearchAdsRequest\x1a\x15.ad.SearchAdsResponseB0Z.78-pflops/services/ad_service/pb/ad_service/pbb\x06proto3"

var (
	file_proto_ad_proto_rawDescOnce sync.Once
	file_proto_ad_proto_rawDescData []byte
)

func file_proto_ad_proto_rawDescGZIP() []byte {
	file_proto_ad_proto_rawDescOnce.Do(func() {
		file_proto_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)))
	})
	return file_proto_ad_proto_rawDescData
}

var file_proto_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ad_proto_goTypes = []any{
	(*Ad)(nil),                // 0: ad.Ad
	(*CreateAdRequest)(nil),   // 1: ad.CreateAdRequest
	(*CreateAdResponse)(nil),  // 2: ad.CreateAdResponse
	(*GetAdRequest)(nil),      // 3: ad.GetAdRequest
	(*GetAdResponse)(nil),     // 4: ad.GetAdResponse
	(*SearchAdsRequest)(nil),  // 5: ad.SearchAdsRequest
	(*SearchAdsResponse)(nil), // 6: ad.SearchAdsResponse
}
var file_proto_ad_proto_depIdxs = []int32{
	0, // 0: ad.CreateAdResponse.ad:type_name -> ad.Ad
	0, // 1: ad.GetAdResponse.ad:type_name -> ad.Ad
	0, // 2: ad.SearchAdsResponse.ads:type_name -> ad.Ad
	1, // 3: ad.AdService.CreateAd:input_type -> ad.CreateAdRequest
	3, // 4: ad.AdService.GetAd:input_type -> ad.GetAdRequest
	5, // 5: ad.AdService.SearchAds:input_type -> ad.SearchAdsRequest
	2, // 6: ad.AdService.CreateAd:output_type -> ad.CreateAdResponse
	4, // 7: ad.AdService.GetAd:output_type -> ad.GetAdResponse
	6, // 8: ad.AdService.SearchAds:output_type -> ad.SearchAdsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ad_proto_init() }
func file_proto_ad_proto_init() {
	if File_proto_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ad_proto_goTypes,
		DependencyIndexes: file_proto_ad_proto_depIdxs,
		MessageInfos:      file_proto_ad_proto_msgTypes,
	}.Build()
	File_proto_ad_proto = out.File
	file_proto_ad_proto_goTypes = nil
	file_proto_ad_proto_depIdxs = nil
}
