# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"_\n\x12UploadMediaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\"E\n\x13UploadMediaResponse\x12\x10\n\x08media_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"#\n\x0fGetMediaRequest\x12\x10\n\x08media_id\x18\x01 \x01(\t\"]\n\x10GetMediaResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\"7\n\x12\x44\x65leteMediaRequest\x12\x10\n\x08media_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"7\n\x13\x44\x65leteMediaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"#\n\x10ListMediaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\":\n\x11ListMediaResponse\x12%\n\x0bmedia_items\x18\x01 \x03(\x0b\x32\x10.media.MediaItem\"e\n\tMediaItem\x12\x10\n\x08media_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x13\n\x0bupload_date\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\"!\n\rGetUrlRequest\x12\x10\n\x08media_id\x18\x01 \x01(\t\"/\n\x0eGetUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08media_id\x18\x02 \x01(\t2\xce\x02\n\x0cMediaService\x12\x44\n\x0bUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x1a.media.UploadMediaResponse\x12;\n\x08GetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponse\x12\x44\n\x0b\x44\x65leteMedia\x12\x19.media.DeleteMediaRequest\x1a\x1a.media.DeleteMediaResponse\x12>\n\tListMedia\x12\x17.media.ListMediaRequest\x1a\x18.media.ListMediaResponse\x12\x35\n\x06GetUrl\x12\x14.media.GetUrlRequest\x1a\x15.media.GetUrlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADMEDIAREQUEST']._serialized_start=22
  _globals['_UPLOADMEDIAREQUEST']._serialized_end=117
  _globals['_UPLOADMEDIARESPONSE']._serialized_start=119
  _globals['_UPLOADMEDIARESPONSE']._serialized_end=188
  _globals['_GETMEDIAREQUEST']._serialized_start=190
  _globals['_GETMEDIAREQUEST']._serialized_end=225
  _globals['_GETMEDIARESPONSE']._serialized_start=227
  _globals['_GETMEDIARESPONSE']._serialized_end=320
  _globals['_DELETEMEDIAREQUEST']._serialized_start=322
  _globals['_DELETEMEDIAREQUEST']._serialized_end=377
  _globals['_DELETEMEDIARESPONSE']._serialized_start=379
  _globals['_DELETEMEDIARESPONSE']._serialized_end=434
  _globals['_LISTMEDIAREQUEST']._serialized_start=436
  _globals['_LISTMEDIAREQUEST']._serialized_end=471
  _globals['_LISTMEDIARESPONSE']._serialized_start=473
  _globals['_LISTMEDIARESPONSE']._serialized_end=531
  _globals['_MEDIAITEM']._serialized_start=533
  _globals['_MEDIAITEM']._serialized_end=634
  _globals['_GETURLREQUEST']._serialized_start=636
  _globals['_GETURLREQUEST']._serialized_end=669
  _globals['_GETURLRESPONSE']._serialized_start=671
  _globals['_GETURLRESPONSE']._serialized_end=718
  _globals['_MEDIASERVICE']._serialized_start=721
  _globals['_MEDIASERVICE']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
